Repository bit-bots/bitbots_navigation, pull requests merged in 2020-03, with the labels that each got.

#41 bitbots_visual_compass: Update py version in cfg
  bitbots_localization/cfg/localization.cfg
  bitbots_localization/package.xml
  bitbots_localization/scripts/feature_publisher.py
  bitbots_localization/scripts/statistics.py
  bitbots_localization_handler/localization_handler.py
  bitbots_visual_compass/CMakeLists.txt
  bitbots_visual_compass/cfg/visualCompass.cfg
  bitbots_visual_compass/package.xml
  bitbots_visual_compass/scripts/connector.py
  bitbots_visual_compass/scripts/davros_recorder.py
  bitbots_visual_compass/scripts/demo_viz.py
  bitbots_visual_compass/src/evaluation_data_loader.py
  bitbots_visual_compass/src/key_point_converter.py
  bitbots_visual_compass/src/videocv.py
  bitbots_visual_compass/src/visual_compass_setup.py
  bitbots_visual_compass/src/visual_compass_startup.py
  bitbots_visual_compass/src/worker/__init__.py
  bitbots_visual_compass/src/worker/interface.py
  bitbots_visual_compass/src/worker/matcher/akaze_matcher.py
  bitbots_visual_compass/src/worker/matcher/interface.py
  bitbots_visual_compass/src/worker/matcher/orb_matcher.py
Labels: bug

#45 Localization: Field parameter
  bitbots_localization/config/config.yaml
  bitbots_localization/config/fields/feldraum.yaml
  bitbots_localization/launch/localization.launch
Labels: enhancement

#46 Localization: Fix arg bug
  bitbots_localization/launch/localization.launch
Labels: bug

#47 Localization: Catch tf exception
  bitbots_localization/src/localization.cpp
Labels: bug

#43 Localization: Refactor motion model
  bitbots_localization/CMakeLists.txt
  bitbots_localization/cfg/localization.cfg
  bitbots_localization/config/config.yaml
  bitbots_localization/include/bitbots_localization/MotionModel.h
  bitbots_localization/include/bitbots_localization/localization.h
  bitbots_localization/include/bitbots_localization/tools.h
  bitbots_localization/src/MotionModel.cpp
  bitbots_localization/src/localization.cpp
  bitbots_localization/src/tools.cpp
Labels: refactoring

#44 Localization: Refactor and clean up transforms
  bitbots_localization/include/bitbots_localization/localization.h
  bitbots_localization/msg/Evaluation.msg
  bitbots_localization/src/localization.cpp
Labels: refactoring

#53 Bounds not realistic for percentage value
  bitbots_localization/cfg/localization.cfg
  bitbots_localization/config/config.yaml
Labels: bug

#54 Move angle stuff to robot state
  bitbots_localization/include/bitbots_localization/RobotState.h
  bitbots_localization/package.xml
  bitbots_localization/src/MotionModel.cpp
  bitbots_localization/src/RobotState.cpp
Labels: refactoring

#56 Refactor/misc refactor
  bitbots_localization/CMakeLists.txt
  bitbots_localization/cfg/localization.cfg
  bitbots_localization/config/config.yaml
  bitbots_localization/include/bitbots_localization/ObservationModel.h
  bitbots_localization/include/bitbots_localization/localization.h
  bitbots_localization/launch/evaluation.launch
  bitbots_localization/msg/Evaluation.msg
  bitbots_localization/src/ObservationModel.cpp
  bitbots_localization/src/localization.cpp
  bitbots_localization/src/tools.cpp
Labels: refactoring

#57 Localization: Refactoring part 2
  bitbots_localization/cfg/localization.cfg
  bitbots_localization/config/config.yaml
  bitbots_localization/include/bitbots_localization/ObservationModel.h
  bitbots_localization/include/bitbots_localization/localization.h
  bitbots_localization/include/bitbots_localization/map.h
  bitbots_localization/scripts/abs.py
  bitbots_localization/scripts/barplot.py
  bitbots_localization/scripts/boxplot.py
  bitbots_localization/scripts/evaluation.sh
  bitbots_localization/scripts/plots.py
  bitbots_localization/scripts/plots2.py
  bitbots_localization/scripts/plots3.py
  bitbots_localization/scripts/statistics.py
  bitbots_localization/src/ObservationModel.cpp
  bitbots_localization/src/localization.cpp
  bitbots_localization/src/map.cpp
  bitbots_visual_compass/src/visual_compass_filter.py
Labels: refactoring

#60 Localization: Clear measurments only one
  bitbots_localization/src/ObservationModel.cpp
Labels: refactoring
